### ISSUE TITLE
set option DialWithDialFunc and DialWithExplicitTLS client will hang on List

### ISSUE THREAD

**Issue by labulakalia** [jlaffaye/ftp#425]
**Describe the bug**
set option DialWithDialFunc and DialWithExplicitTLS client will hang on List

**To Reproduce**
start docker 
```
version: "3"
services:
  ftps: # 
    image: ghcr.io/haravich/custom-ftp-server:20250223
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    ports:
      - "20-21:20-21"
      - "20000-20010:20000-20010"
    environment:
      FTP_MODE: ftps
      PASV_MIN_PORT: 20000
      PASV_MAX_PORT: 20010
```
hang on 
```
	ftpConn, err := ftp.Dial("127.0.0.1:21",
		ftp.DialWithDialFunc(func(network, address string) (net.Conn, error) {
			return net.Dial(network,address)
		}),
		ftp.DialWithExplicitTLS(&tls.Config{InsecureSkipVerify: true}),
		ftp.DialWithDebugOutput(os.Stdout),
	)

	if err != nil {
		log.Panicln(err)
	}
	user := "ftpuser"
	password := "admin"
	err = ftpConn.Login(user, password)
	if err != nil {
		log.Panicln(err)
	}
	entries, err := ftpConn.List("/")
```

**Expected behavior**

**FTP server**
- Name and version:
- Public URL if applicable

**Debug output**
```
220 Welcome to FTP Server
USER ftpuser
331 Please specify the password.
PASS admin
230 Login successful.
FEAT
211-Features:
 AUTH TLS
 EPRT
 EPSV
 MDTM
 PASV
 PBSZ
 PROT
 REST STREAM
 SIZE
 TVFS
 UTF8
211 End
TYPE I
200 Switching to Binary mode.
OPTS UTF8 ON
200 Always in UTF8 mode.
PBSZ 0
200 PBSZ set to 0.
PROT P
200 PROT now Private.
2025/02/26 10:54:11 ftp conn list
EPSV
229 Entering Extended Passive Mode (|||20016|)
```

**Additional context**
